export type BaziRuleSourceType = "ctext_verbatim" | "ctext_derived" | "internal_heuristic";
export type BaziRuleEngineStatus = "supported" | "partial" | "not_supported";
export type BaziRuleLevel = "principle" | "condition" | "resolver_policy" | "warning";

export type BaziInteractionRule = {
  ruleId: string;
  topic: "hehua" | "hechong" | "muku" | "yongshen_change" | "resolver_order";
  sourceWork: string;
  sourceChapter: string;
  sourceUrl: string;
  sourceLines?: string;
  sourceAnchor?: string;
  canonicalChinese?: string;
  sourceType: BaziRuleSourceType;
  engineStatus: BaziRuleEngineStatus;
  confidence: "high" | "medium" | "low";
  ruleLevel: BaziRuleLevel;
  shortSource?: string;
  thaiSummary: string;
  engineMeaning: string;
  appliesTo: string[];
};

const ZPZQ = "https://ctext.org/wiki.pl?chapter=974137&if=en";

export const BAZI_INTERACTION_RULES: BaziInteractionRule[] = [
  {
    ruleId: "ZPZQ-HE-000",
    topic: "hehua",
    sourceWork: "子平真詮評注",
    sourceChapter: "四．論十干配合性情 / 五．論十干合而不合",
    sourceUrl: ZPZQ,
    sourceLines: "129-130",
    sourceAnchor: "四．論十干配合性情",
    canonicalChinese: "合化之義",
    sourceType: "ctext_derived",
    engineStatus: "supported",
    confidence: "high",
    ruleLevel: "principle",
    shortSource: "合化之義",
    thaiSummary: "ห้าคู่ก้านฟ้า 甲己/乙庚/丙辛/丁壬/戊癸 มีหลักแปรธาตุ แต่ต้องให้ resolver ตรวจเงื่อนไขก่อนฟันธง",
    engineMeaning: "Base principle for the five heavenly-stem combinations; transformation is only promoted after condition checks.",
    appliesTo: ["天干五合", "合化", "transform_supported"],
  },
  {
    ruleId: "ZPZQ-HE-001",
    topic: "hehua",
    sourceWork: "子平真詮評注",
    sourceChapter: "五．論十干合而不合",
    sourceUrl: ZPZQ,
    sourceLines: "132-133",
    sourceAnchor: "五．論十干合而不合",
    canonicalChinese: "隔於有所間",
    sourceType: "ctext_derived",
    engineStatus: "partial",
    confidence: "high",
    ruleLevel: "condition",
    shortSource: "隔於有所間",
    thaiSummary: "ก้านฟ้าฮะกัน แต่ถ้ามีก้านอื่นคั่นและขวางแรง ฮะนั้นไม่ออกเต็ม",
    engineMeaning: "When a five-stem combination is separated by an intervening disruptive stem, classify it as blocked rather than transformed.",
    appliesTo: ["天干五合", "合而不合", "blocked_by_intervening_stem"],
  },
  {
    ruleId: "ZPZQ-HE-002",
    topic: "hehua",
    sourceWork: "子平真詮評注",
    sourceChapter: "五．論十干合而不合",
    sourceUrl: ZPZQ,
    sourceLines: "134",
    sourceAnchor: "五．論十干合而不合",
    canonicalChinese: "隔位太遠",
    sourceType: "ctext_derived",
    engineStatus: "partial",
    confidence: "high",
    ruleLevel: "condition",
    shortSource: "隔位太遠",
    thaiSummary: "ฮะที่อยู่ไกลกันมากยังมีนัย แต่แรงอ่อน ไม่ควรตัดเป็นแปรธาตุ",
    engineMeaning: "Remote stem combinations are weak binding signals and must not be promoted to true transformation.",
    appliesTo: ["天干五合", "distance", "remote_weak"],
  },
  {
    ruleId: "ZPZQ-HE-003",
    topic: "hehua",
    sourceWork: "子平真詮評注",
    sourceChapter: "五．論十干合而不合",
    sourceUrl: ZPZQ,
    sourceLines: "136-139",
    sourceAnchor: "五．論十干合而不合",
    canonicalChinese: "本身之合",
    sourceType: "ctext_derived",
    engineStatus: "supported",
    confidence: "high",
    ruleLevel: "condition",
    shortSource: "本身之合",
    thaiSummary: "日主ฮะของตัวเอง ไม่เหมือนถูกก้านอื่น合去 ต้องแยกกรณี",
    engineMeaning: "A Day Master's own combination is not automatically treated as another stem taking the useful god away.",
    appliesTo: ["天干五合", "day_master_combination", "合去"],
  },
  {
    ruleId: "ZPZQ-HE-004",
    topic: "hehua",
    sourceWork: "子平真詮評注",
    sourceChapter: "五．論十干合而不合",
    sourceUrl: ZPZQ,
    sourceLines: "138",
    sourceAnchor: "五．論十干合而不合",
    canonicalChinese: "爭合妒合",
    sourceType: "ctext_derived",
    engineStatus: "partial",
    confidence: "high",
    ruleLevel: "condition",
    shortSource: "爭合妒合",
    thaiSummary: "มีหลายก้านแย่งฮะกัน ความสัมพันธ์ไม่บริสุทธิ์ ไม่ควรตัดเป็นแปรธาตุเต็ม",
    engineMeaning: "Multiple stems competing for the same combination partner create contested combination status.",
    appliesTo: ["天干五合", "contested", "爭合", "妒合"],
  },
  {
    ruleId: "HK-HE-CTRL-001",
    topic: "hehua",
    sourceWork: "Hourkey internal design",
    sourceChapter: "Hehua visible control v1",
    sourceUrl: "internal",
    sourceAnchor: "Hourkey hehua visible control v1",
    canonicalChinese: "visible_stem_controls_transform_element",
    sourceType: "internal_heuristic",
    engineStatus: "supported",
    confidence: "medium",
    ruleLevel: "resolver_policy",
    thaiSummary: "ถ้ามีก้านที่คุมธาตุแปร透ออก และมีกำลังรากใกล้จุดฮะ ให้ตัดว่าคุมแรงแปรได้; ถ้าไกลหรือไร้ราก ให้ถือว่าคุมไม่อยู่",
    engineMeaning: "Strength-based visible controlling stem policy used to decide whether a stem can block transformation support.",
    appliesTo: ["天干五合", "visible_stem_controls_transform_element", "visible_stem_control_too_weak"],
  },
  {
    ruleId: "ZPZQ-XCH-001",
    topic: "hechong",
    sourceWork: "子平真詮評注",
    sourceChapter: "七．論刑衝會合解法",
    sourceUrl: ZPZQ,
    sourceLines: "143-144",
    sourceAnchor: "七．論刑衝會合解法",
    canonicalChinese: "會合可以解衝",
    sourceType: "ctext_derived",
    engineStatus: "not_supported",
    confidence: "high",
    ruleLevel: "condition",
    shortSource: "會合可以解衝",
    thaiSummary: "สามฮะ/六合 สามารถแก้แรงชงหรือ刑ได้ในบางเงื่อนไข",
    engineMeaning: "Combinations may resolve clashes or punishments, but the resolver must inspect the concrete branch graph.",
    appliesTo: ["六合", "三合", "六沖", "刑", "貪合忘冲"],
  },
  {
    ruleId: "ZPZQ-XCH-002",
    topic: "hechong",
    sourceWork: "子平真詮評注",
    sourceChapter: "七．論刑衝會合解法",
    sourceUrl: ZPZQ,
    sourceLines: "145",
    sourceAnchor: "七．論刑衝會合解法",
    canonicalChinese: "因解而反得刑衝",
    sourceType: "ctext_derived",
    engineStatus: "not_supported",
    confidence: "high",
    ruleLevel: "condition",
    shortSource: "因解而反得刑衝",
    thaiSummary: "บางครั้งตัวที่มาแก้ กลับดึงตัวหนึ่งออกไปจนเหลืออีกแรง刑/冲 ทำงาน",
    engineMeaning: "Resolution can expose a different punishment/clash; do not simply delete all conflicts when a combination exists.",
    appliesTo: ["六合", "刑", "六沖", "secondary_conflict"],
  },
  {
    ruleId: "ZPZQ-XCH-003",
    topic: "hechong",
    sourceWork: "子平真詮評注",
    sourceChapter: "七．論刑衝會合解法",
    sourceUrl: ZPZQ,
    sourceLines: "146",
    sourceAnchor: "七．論刑衝會合解法",
    canonicalChinese: "會合不能解",
    sourceType: "ctext_derived",
    engineStatus: "not_supported",
    confidence: "high",
    ruleLevel: "condition",
    shortSource: "會合不能解",
    thaiSummary: "ไม่ใช่ทุกฮะจะแก้ชงได้ ถ้าฮะนั้นถูกดึงไปเข้ากลุ่มอื่นแล้ว ชงเดิมอาจกลับมาทำงาน",
    engineMeaning: "A combination that is itself absorbed by another stronger combination may fail to resolve the original clash.",
    appliesTo: ["六合", "三合", "六沖", "resolver_graph"],
  },
  {
    ruleId: "ZPZQ-MK-001",
    topic: "muku",
    sourceWork: "子平真詮評注",
    sourceChapter: "十七．論墓庫刑衝之說",
    sourceUrl: ZPZQ,
    sourceLines: "207-211",
    sourceAnchor: "十七．論墓庫刑衝之說",
    canonicalChinese: "刑衝未必成格",
    sourceType: "ctext_derived",
    engineStatus: "partial",
    confidence: "high",
    ruleLevel: "condition",
    shortSource: "刑衝未必成格",
    thaiSummary: "คลัง 辰戌丑未 โดนชง ไม่ได้แปลว่าเปิดคลังแล้วดีเสมอ ต้องดูของที่ออกมาเป็น用หรือ忌",
    engineMeaning: "Storage clash is not automatically beneficial; evaluate revealed/stirred hidden stems against useful/avoid elements.",
    appliesTo: ["墓庫", "辰戌", "丑未", "open_close", "useful_god_impact"],
  },
  {
    ruleId: "ZPZQ-YC-001",
    topic: "yongshen_change",
    sourceWork: "子平真詮評注",
    sourceChapter: "十．論用神變化 / 十六．論雜氣如何取用",
    sourceUrl: ZPZQ,
    sourceLines: "170-171,201-206",
    sourceAnchor: "十．論用神變化 / 十六．論雜氣如何取用",
    canonicalChinese: "用神非變化不靈",
    sourceType: "ctext_derived",
    engineStatus: "partial",
    confidence: "high",
    ruleLevel: "principle",
    shortSource: "用神非變化不靈",
    thaiSummary: "用神/格局 ต้องดูการแปรจาก透干และ會支 ไม่ใช่อ่านเดือนดิบอย่างเดียว",
    engineMeaning: "Useful-god and structure judgement must account for transformations, visible stems, and branch combinations before final interpretation.",
    appliesTo: ["用神", "格局", "透干", "會支"],
  },
  {
    ruleId: "HK-ORDER-001",
    topic: "resolver_order",
    sourceWork: "Hourkey internal design",
    sourceChapter: "Resolver order v1",
    sourceUrl: "internal",
    sourceAnchor: "Hourkey deterministic resolver order v1",
    canonicalChinese: "resolver_order_v1",
    sourceType: "internal_heuristic",
    engineStatus: "partial",
    confidence: "medium",
    ruleLevel: "resolver_policy",
    thaiSummary: "ลำดับตัดสินของระบบ: 三會/三合 → 六合 → 六沖 → 刑 → 害/破 เป็น design choice ต้องติดป้าย ไม่อ้างว่าเป็นคำตำราโดยตรง",
    engineMeaning: "Explicit resolver ordering used to make the deterministic engine stable and testable.",
    appliesTo: ["resolution_order", "hechongResolver"],
  },
];

export function getBaziInteractionRule(ruleId: string): BaziInteractionRule | undefined {
  return BAZI_INTERACTION_RULES.find((r) => r.ruleId === ruleId);
}

export function baziRulesByTopic(topic: BaziInteractionRule["topic"]): BaziInteractionRule[] {
  return BAZI_INTERACTION_RULES.filter((r) => r.topic === topic);
}
