export declare const PRESENTATION_VERSION: "ziwei-hourly-type-c-v1";
export declare const PRESENTATION_CATALOG_SHA256: "efea1c6c05c24867ce1df8e5ce5c639266a9544118ee8dc091f69c94adbdbd88";
export declare const MAX_LOCKSCREEN_COPY_UTF8_BYTES: 360;
export declare const READABLE_COPY_VERSION: "ziwei-hourly-readable-copy-v1";
export declare const READABLE_CLOCK_COPY_VERSION: "ziwei-hourly-readable-copy-v2";
export declare const READABLE_COPY_CATALOG_SHA256: "23ea576b5cd9fb95c7102315620980dff1637e11540d7f07d10d090eb1f732e6";
export declare const SUPPORTED_LOCALES: readonly string[];
export declare function buildZiweiHourlyPresentation(locale: string, snapshot: unknown): Readonly<Record<string, unknown>>;
export declare function buildZiweiHourlyTypeCCopy(locale: string, snapshot: unknown): Readonly<{ title: string; body: string }>;
export declare function buildZiweiHourlyReadableCopy(locale: string, snapshot: unknown): Readonly<{ title: string; body: string }>;
export declare function buildZiweiHourlyReadableClockCopy(locale: string, snapshot: unknown): Readonly<{ title: string; body: string }>;
export declare function resolveFlowStarPresentation(locale: string, star: unknown, palace?: unknown, branch?: unknown): Readonly<Record<string, unknown>>;
export declare function resolvePalacePresentation(locale: string, palace: unknown): Readonly<Record<string, unknown>>;
export declare function resolveSihuaPresentation(locale: string, entry: unknown): Readonly<Record<string, unknown>>;
