#!/usr/bin/env node
import nextEnv from "@next/env";
const {loadEnvConfig}=nextEnv;loadEnvConfig(process.cwd(),false,console);
const [{pool},{decryptAuthDelivery},{sendResetEmail},{sendSms}]=await Promise.all([import("../../src/lib/db.ts"),import("../../src/lib/auth-delivery-outbox.ts"),import("../../src/lib/email-service.ts"),import("../../src/lib/thaibulksms-sms.ts")]);
const once=process.argv.includes("--once"),batchSize=Math.max(1,Math.min(50,Number(process.env.AUTH_DELIVERY_BATCH_SIZE||10)));
async function claim(){const client=await pool.connect();try{await client.query("BEGIN");await client.query(`UPDATE auth_delivery_outbox SET status='waiting',locked_at=NULL,updated_at=now() WHERE status='processing' AND locked_at<now()-interval '10 minutes'`);const rows=(await client.query<{id:string;payload_ciphertext:string;attempts:number}>(`SELECT id,payload_ciphertext,attempts FROM auth_delivery_outbox WHERE status='waiting' AND available_at<=now() ORDER BY created_at FOR UPDATE SKIP LOCKED LIMIT $1`,[batchSize])).rows;if(rows.length)await client.query(`UPDATE auth_delivery_outbox SET status='processing',locked_at=now(),attempts=attempts+1,updated_at=now() WHERE id=ANY($1::uuid[])`,[rows.map((row)=>row.id)]);await client.query("COMMIT");return rows;}catch(error){await client.query("ROLLBACK").catch(()=>null);throw error;}finally{client.release();}}
async function deliver(row:{id:string;payload_ciphertext:string;attempts:number}){try{const payload=decryptAuthDelivery(row.payload_ciphertext);if(payload.channel==="email"){const result=await sendResetEmail({to:payload.destination,name:payload.name,link:payload.link});if(result.error)throw new Error("email_provider_failed");}else{const result=await sendSms({to:payload.destination,message:`รีเซ็ตรหัส hourkey: ${payload.link} ใช้ได้ 1 ชม.`});if(!result.ok)throw new Error("sms_provider_failed");}await pool.query(`DELETE FROM auth_delivery_outbox WHERE id=$1`,[row.id]);console.log(JSON.stringify({event:"auth_delivery_sent",id:row.id,channel:payload.channel}));}catch{const attempts=row.attempts+1,failed=attempts>=5,delay=Math.min(3600,30*2**Math.min(attempts,6));await pool.query(`UPDATE auth_delivery_outbox SET status=$2,available_at=now()+($3::text||' seconds')::interval,locked_at=NULL,last_error='delivery_failed',payload_ciphertext=CASE WHEN $2='failed' THEN '' ELSE payload_ciphertext END,updated_at=now() WHERE id=$1`,[row.id,failed?"failed":"waiting",delay]);console.error(JSON.stringify({event:"auth_delivery_failed",id:row.id,attempts,terminal:failed}));}}
async function cycle(){for(const row of await claim())await deliver(row);}
if(once){await cycle();await pool.end();}else{console.log(JSON.stringify({event:"auth_delivery_ready",batchSize}));await cycle();setInterval(()=>void cycle().catch((error)=>console.error(error)),5000);}
