import assert from "node:assert/strict";
import { createRequire } from "node:module";
const require = createRequire(import.meta.url);
const runtime = require("../src/lib/qimen-seasonal-vigor.cjs");
const stems = "甲乙丙丁戊己庚辛壬癸";
const branches = "子丑寅卯辰巳午未申酉戌亥";
const stars = {
  TIAN_PENG: "水", TIAN_RUI: "土", TIAN_CHONG: "木", TIAN_FU: "木", TIAN_QIN: "土",
  TIAN_XIN: "金", TIAN_ZHU: "金", TIAN_REN: "土", TIAN_YING: "火",
};
// Literal source-derived order for 旺 相 休 囚 廢, not generated by production relations.
const orders = { 子: "金水土火木", 丑: "火土木水金", 寅: "水木金土火", 卯: "水木金土火",
  辰: "火土木水金", 巳: "木火水金土", 午: "木火水金土", 未: "火土木水金",
  申: "土金火木水", 酉: "土金火木水", 戌: "火土木水金", 亥: "金水土火木" };
const labels = ["旺", "相", "休", "囚", "廢"];
assert.equal(typeof runtime.nineStarVigorForMonthPillar, "function", "component classification must take a validated month pillar, not a cached chart array");
let cases = 0;
for (let b = 0; b < branches.length; b++) for (let s = b % 2; s < stems.length; s += 2) {
  const branch = branches[b] as keyof typeof orders;
  const pillar = `${stems[s]}${branch}`;
  const actual = runtime.nineStarVigorForMonthPillar(pillar);
  assert.equal(actual.monthPillarZh, pillar);
  assert.equal(actual.monthBranch, branch);
  assert.equal(actual.method, runtime.NINE_STAR_METHOD);
  assert.equal(actual.sourceSha256, runtime.NINE_STAR_SOURCE_SHA256);
  assert.deepEqual(Object.keys(actual.byStarCode).sort(), Object.keys(stars).sort());
  for (const [star, element] of Object.entries(stars)) {
    assert.equal(actual.byStarCode[star], labels[orders[branch].indexOf(element)], `${pillar}/${star}`);
    cases++;
  }
  assert.ok(Object.isFrozen(actual) && Object.isFrozen(actual.byStarCode));
}
assert.equal(runtime.nineStarVigorForMonthPillar("甲午").byStarCode.TIAN_FU, "旺");
assert.equal(runtime.nineStarVigorForMonthPillar("甲午").byStarCode.TIAN_QIN, "廢", "center 天禽 remains a real earth star with its own state");
for (const pillar of [null, undefined, "", "午", "乙午", "甲巳", "甲午 ", " 甲午", "2026-06", "__proto__", {}, ["甲午"]]) {
  assert.throws(() => runtime.nineStarVigorForMonthPillar(pillar), /qimen_seasonal_month_pillar_invalid/u);
}
console.log(`QIMEN_NINE_STAR_COMPONENT_MONTH_OK cases=${cases} all_60_pillars=PASS center=PASS`);
