import { readFileSync } from "node:fs";
import { join } from "node:path";

const root = process.cwd();
const route = readFileSync(join(root, "src/app/api/qimen/sifu/route.ts"), "utf8");

function assertHas(needle: string, label: string) {
  if (!route.includes(needle)) {
    throw new Error(`missing ${label}: ${needle}`);
  }
}

function assertNotHas(needle: string, label: string) {
  if (route.includes(needle)) {
    throw new Error(`unexpected ${label}: ${needle}`);
  }
}

function assert(condition: boolean, label: string) {
  if (!condition) throw new Error(label);
}

function functionBlock(name: string) {
  const start = route.indexOf(`function ${name}`);
  if (start < 0) throw new Error(`missing function block: ${name}`);
  const brace = route.indexOf("{", start);
  let depth = 0;
  for (let i = brace; i < route.length; i++) {
    if (route[i] === "{") depth++;
    if (route[i] === "}") depth--;
    if (depth === 0) return route.slice(start, i + 1);
  }
  throw new Error(`unterminated function block: ${name}`);
}

function assertBlockHas(block: string, needle: string, label: string) {
  if (!block.includes(needle)) throw new Error(`missing ${label}: ${needle}`);
}

function assertBlockNotHas(block: string, needle: string, label: string) {
  if (block.includes(needle)) throw new Error(`unexpected ${label}: ${needle}`);
}

const stemFormatter = functionBlock("formatStemResponse");
const timeContextFormatter = functionBlock("formatQimenTimeContext");
const uiFlagsFormatter = functionBlock("formatQimenUiFlags");
const mergedUiContextFlags = functionBlock("qimenMergedUiContextFlags");
const capabilitiesFormatter = functionBlock("formatQimenCapabilities");
const classicalCoverageFormatter = functionBlock("formatQimenClassicalCoverage");
const advancedLayerFormatter = functionBlock("formatAdvancedQimenLayers");
const advancedReadinessFormatter = functionBlock("formatAdvancedQimenReadiness");
const advancedLayerLabelFormatter = functionBlock("formatAdvancedLayerLabel");
const branchTokens = functionBlock("qimenBranchTokens");
const xiuFormatter = functionBlock("qimenXiuLabel");
const timeBranchFormatter = functionBlock("qimenTimeBranch");
const palaceLineFormatter = functionBlock("formatPalaceLine");
const traceItemFormatter = functionBlock("formatTraceItem");
const sifuChartContextGuard = functionBlock("qimenSifuChartContextGuard");
const sifuApplyChartContextGuard = functionBlock("qimenSifuApplyChartContextGuard");
const sifuScoreLine = functionBlock("qimenSifuScoreLine");
const beginnerFormatter = functionBlock("formatBeginnerReading");
const sourceRefFormatter = functionBlock("sourceRefText");
const fushiLineFormatter = functionBlock("qimenFushiLine");
const chartAxisFormatter = functionBlock("qimenChartAxisLine");
const palaceSignalFormatter = functionBlock("formatPalaceSignalEvidence");
const selectedPalaceCueFormatter = functionBlock("formatSelectedPalaceDecisionCue");
const flagBranchEvidenceFormatter = functionBlock("formatQimenFlagBranchEvidence");
const palaceBranchEvidenceSummary = functionBlock("formatPalaceBranchEvidenceSummary");
const branchEvidenceLayerLabel = functionBlock("qimenBranchEvidenceLayerLabel");

assertHas("function formatBeginnerReading", "beginner formatter");
assertHas("function qimenSifuChartContextGuard", "Sifu prompt DMY context guard");
assertHas("function qimenSifuApplyChartContextGuard", "Sifu prompt guarded beginner reading");
assertBlockHas(sifuApplyChartContextGuard, "summary_th: caveat", "DMY/context guard must replace stale actionable summary with caveat only");
assertBlockNotHas(sifuApplyChartContextGuard, "summary ? `${summary} · ${caveat}` : caveat", "DMY/context guard must not append stale original summary");
assertHas("function qimenSifuScoreLine", "Sifu prompt score line policy");
assertHas("function qimenFushiLine", "Thai-first fushi formatter");
assertHas("function qimenChartAxisLine", "Thai-first chart axis formatter");
assertHas("function formatSelectedPalaceDecisionCue", "selected palace decision cue formatter");
assertHas("function formatPalaceSignalEvidence", "palace signal evidence formatter");
assertHas("function formatQimenFlagBranchEvidence", "branch evidence formatter");
assertHas("function formatPalaceBranchEvidenceSummary", "selected palace branch evidence summary formatter");
assertHas("branch_evidence", "Sifu route reads backend branch evidence");
assertHas("beginner_reading", "engine beginner_reading payload");
assertHas("สถานะอ่านเร็ว 入門", "Thai-first beginner status");
assertHas("เพราะอะไร", "Thai reasons line");
assertHas("ต้องเช็กต่อ", "check-next line");
assertHas("นโยบายอ่านเร็ว 入門", "Thai beginner coverage line");
assertHas("ใช้เป็นตัวหลักไม่ได้", "non-actionable Thai policy");
assertHas("สถานะอ่านเร็วบอกว่าใช้เป็นตัวหลักไม่ได้", "actionability guard in Thai");
assertHas("ไม่มีคะแนนรวมจากระบบ", "engine-score guard in Thai");
assertHas("no_score_mutation", "score mutation policy");
assertHas("ระบบยังไม่มีข้อมูลอ่านเร็วที่เชื่อถือได้", "fallback beginner copy avoids raw field names");
assertNotHas("guard fields:", "raw guard field label must not reach Sifu prompt");
assertHas("qimen_trace", "source trace payload");
assertHas("classical_flags", "classical flags payload");
assertHas("สัญญาณแหล่งอ้างอิง", "bounded Thai source flags line");
assertHas("ห้ามแนะนำให้ใช้ทิศนั้นเป็นตัวหลัก", "non-actionable answer guard");
assertHas("ห้ามแก้คะแนน", "no score mutation answer guard");
assertHas("ประตู + ดาว + เทพ + ก้าน + ป้ายสัญญาณจากระบบ", "real palace evidence guard");
assertHas("ห้ามตอบจากคะแนนอย่างเดียว", "selected direction must not answer from score only");
assertHas("ผังวัน/เดือน/ปีถูกส่งมาแบบอ่านประกอบเท่านั้น", "answer guard covers DMY context-only prompt");
assertHas("ต้องเช็กผังยาม 時家 ก่อนลงมือ", "answer guard tells Sifu to verify hour chart before action");
assertHas("ข้อมูลผังจากระบบคำนวณคือหลักตัดสิน", "chart data source-of-truth header");
assertHas("อ่านจาก \"ผังเวลา (QiMen Chart)\" ก่อนเสมอ", "answer guard says chart first");
assertHas("ชุดแหล่งอ้างอิงมีไว้แปลความหมาย ไม่ใช่สร้างค่าผังใหม่", "source packet caveat");
assertHas("อ่านจากผังจริงก่อน แล้วใช้ตำราแปลความหมาย", "fallback persona must put real chart before canon");
assertHas("function unwrapQimenPayload", "Sifu route must unwrap wrapped /api/qimen payloads");
assertHas("function qimenPayloadFromRequestPayload", "Sifu route must normalize qimen payload before prompt build");
assertHas("const qimen = qimenPayloadFromRequestPayload(payload)", "Sifu buildPrompt must use normalized qimen payload");
assertHas("value.data.chart || value.data.palaces", "Sifu unwrap recognizes wrapped qimen data shape");
assertHas("ไทยนำจีนรองเสมอ แม้ผู้ใช้เปิดโหมดอังกฤษ", "English mode must still obey Thai-first policy");
assertHas("ไทยนำจีนรองเสมอ แม้ผู้ใช้เปิดโหมดจีน", "Chinese mode must still obey Thai-first policy");
assertNotHas("Reply in English", "Sifu route must not allow English-first Qimen answers");
assertNotHas("用简体中文回答", "Sifu route must not allow Chinese-first Qimen answers");
assertHas("function formatQimenTimeContext", "time context formatter");
assertHas("function formatQimenUiFlags", "ui flags formatter");
assertHas("function formatQimenCapabilities", "capabilities formatter");
assertHas("function formatQimenClassicalCoverage", "classical detector coverage formatter");
assertHas("function formatAdvancedQimenLayers", "advanced qimen palace layers formatter");
assertHas("function formatAdvancedQimenReadiness", "advanced qimen readiness formatter");
assertHas("function formatAdvancedLayerLabel", "advanced qimen layer label formatter");
assertHas("BRANCH_TH_ZH", "Thai-first branch label map");
assertHas("STEM_TH_ZH", "Thai-first stem label map");
assertHas("XIU_TH_ZH", "Thai-first 28 mansions label map");
assertHas("บริบทเวลา 時間標記: ${formatQimenTimeContext(chart)}", "time context line in chart packet");
assertHas("ช่องว่าง 空亡", "Thai-first void label");
assertHas("ม้าเดินทาง 驛馬", "Thai-first sky horse label");
assertHas("คนช่วย 貴人", "Thai-first nobleman label");
assertHas("วัน/ยามปะทะ 日時沖", "Thai-first clash label uses traditional Chinese");
assertNotHas("日時冲", "old simplified clash label");
assertHas("28 ดาวฤกษ์ 二十八宿", "Thai-first 28 mansions label");
assertHas("ใช้เป็นบริบทเวลาจากข้อมูลผังจริงเท่านั้น", "time context is packet-only context");
assertHas("ให้ใช้เฉพาะบรรทัด \"บริบทเวลา 時間標記\" จากข้อมูลผังจริง ห้ามคำนวณเพิ่มเอง", "answer guard blocks time-context recalculation");
assertHas("ป้ายช่วยอ่านจากระบบเป็นข้อมูลประกอบเท่านั้น", "answer guard marks ui flags as metadata only");
assertHas("ห้ามแปลงเป็นคะแนน ห้ามคำนวณเพิ่ม", "answer guard blocks ui flag scoring");
assertHas("ความพร้อมของข้อมูลผัง: มีป้ายช่วยอ่านจากระบบ", "prompt includes engine capabilities line");
assertHas("${formatQimenCapabilities(chart)}", "chart packet includes capabilities formatter output");
assertHas("ความพร้อมตัวตรวจสูตรลึก 格局/四害", "prompt includes classical detector coverage line");
assertHas("${formatQimenClassicalCoverage(chart)}", "chart packet includes classical detector coverage formatter output");
assertHas("สถานะชั้นสูตรใหม่ 深層公式狀態", "prompt includes advanced layer readiness line");
assertHas("${formatAdvancedQimenReadiness(chart, q)}", "chart packet includes advanced readiness formatter output");
assertHas("ชั้นสูตรลึกที่เกิดในวังนี้ 深層標記", "palace prompt includes active advanced layer line");
assertHas("สูตรเตือนที่ระบบตรวจได้", "classical coverage lists guard detector family in Thai");
assertHas("รูปแบบขั้นสูงที่ระบบตรวจได้", "classical coverage lists advanced detector family in Thai");
assertHas("ห้ามฟันธงจากรายการนี้เดี่ยว ๆ", "classical coverage blocks support-list verdict misuse");
assertHas("ถ้าจะกล่าวว่าสูตรใดเกิด ต้องเห็นสูตรนั้นในป้ายสัญญาณ/รูปแบบที่ติดจริงในวัง", "answer guard blocks coverage-as-active-formation misuse");
assertHas("ป้ายช่วยอ่านจากระบบ", "palace formatter includes engine ui flags line");
assertHas("ไม่มีผลกับคะแนน", "ui flags explicitly have no score effect");
assertHas("แหล่งอ้างอิง: ${s.file}:${s.start}-${s.end}", "source packet exposes file and line range");
assertHas("trace.push(`${s.id}=${s.file}:${s.start}-${s.end}`)", "source trace exposes id=file:start-end");
assertBlockHas(timeContextFormatter, "chart?.voids || {}", "time context reads chart voids");
assertBlockHas(timeContextFormatter, "chart?.sky_horse || chart?.skyHorse || {}", "time context reads chart sky_horse");
assertBlockHas(timeContextFormatter, "chart?.nobleman || {}", "time context reads chart nobleman");
assertBlockHas(timeContextFormatter, "chart?.clash || {}", "time context reads chart clash");
assertBlockHas(uiFlagsFormatter, "qimenMergedUiContextFlags(p)", "ui flags formatter reads merged engine ui/context flags");
assertBlockHas(uiFlagsFormatter, "qimenContextFlagIsActive(flag)", "ui flags formatter requires active flags");
assertBlockHas(uiFlagsFormatter, "ไม่มีผลกับคะแนน", "ui flags formatter labels score effect none");
assertBlockHas(capabilitiesFormatter, "chart?.api_capabilities?.qimen_context_flags", "capabilities formatter reads engine capability packet");
assertBlockHas(capabilitiesFormatter, "ไม่มีผลกับคะแนน", "capabilities formatter carries no score mutation policy");
assertBlockHas(capabilitiesFormatter, "ห้ามคำนวณเพิ่ม", "capabilities fallback blocks recalculation");
assertBlockHas(classicalCoverageFormatter, "chart?.classical_p0?.coverage", "classical coverage formatter reads engine classical_p0 coverage packet");
assertBlockHas(classicalCoverageFormatter, "item.category === \"guard_flag\"", "classical coverage formatter separates guard flags");
assertBlockHas(classicalCoverageFormatter, "item.category === \"advanced_formation\"", "classical coverage formatter separates advanced formations");
assertBlockHas(classicalCoverageFormatter, "coverage.caveat_th", "classical coverage formatter includes Thai caveat from engine");
assertBlockHas(classicalCoverageFormatter, "ไม่มีผลกับคะแนน", "classical coverage formatter states no score effect");
assertBlockHas(classicalCoverageFormatter, "ห้ามอ้างว่าระบบตรวจครบ", "classical coverage fallback blocks false coverage claims");
assertBlockNotHas(classicalCoverageFormatter, "score_effect", "classical coverage formatter must not render raw scoring field names");
assertBlockHas(branchTokens, "raw.branch_zh ?? raw.branch", "branch parser reads explicit single branch fields only");
assertBlockHas(branchTokens, "raw.branches_zh ?? raw.branches ?? raw.branch_codes ?? raw.void_zh", "branch parser reads explicit branch list fields only");
assertBlockNotHas(branchTokens, "raw.zh ?? raw.code", "branch parser must not treat generic zh/code as branch fallback");
assertBlockHas(timeContextFormatter, "chart?.void_day_zh || chart?.voidDayZh", "time context supports legacy void day field");
assertBlockHas(timeContextFormatter, "chart?.traveling_horse_day_zh || chart?.traveling_horse_zh", "time context supports legacy sky horse field");
assertBlockHas(xiuFormatter, "chart?.twenty_eight || chart?.twentyEight || {}", "28 mansions read from chart packet");
assertBlockHas(xiuFormatter, "XIU_GROUP_TH_ZH", "28 mansions group Thai-first formatter");
assertBlockHas(xiuFormatter, "ZH_DIR_TH_ZH", "28 mansions direction Thai-first formatter");
assertBlockHas(timeBranchFormatter, "const direct = qimenBranchList(value, \"\")", "time branch tries direct value first");
assertBlockHas(timeBranchFormatter, "return direct || qimenBranchList(fallback, \"ข้อมูลไม่พอ\")", "time branch falls back when direct is empty");
assertHas("ถ้าปฏิกิริยาก้านบอกว่ายังไม่อนุญาตให้ฟันธง", "answer guard checks stem_response non-verdict in Thai");
assertHas("ห้ามใช้คู่ก้านสิบก้านตอบสนอง 十干克應 เป็นคำตัดสิน", "answer guard blocks context-only stem verdict");
assertHas("ให้บอกว่าอ่านประกอบเท่านั้น", "answer guard tells Sifu to label context-only stem");
assertHas("function selectedPalaceIdFromPayload", "selected palace payload helper");
assertHas("วังที่ผู้ใช้เลือก 選宮", "selected palace block Thai-first");
assertHas("ให้เริ่มจากวังที่ผู้ใช้เลือกนี้ก่อน", "selected palace answer contract");
assertHas("formatPalaceLine(selectedPalace", "selected palace uses real palace formatter");
assertHas("formatSelectedPalaceDecisionCue(selectedPalace, selector, chart, systemType)", "selected palace block includes explicit guarded answer cue");
assertHas("labelThZh(p.door_name_th", "door evidence included");
assertHas("labelThZh(p.star_name_th", "star evidence included");
assertHas("function normalizeQimenDeityZh", "Sifu deity Chinese normalizer exists");
assertHas("function normalizeQimenDeityTh", "Sifu deity Thai normalizer exists");
assertHas("normalizeQimenDeityZh(p.deity_zh)", "deity evidence normalizes Chinese glyph before prompt");
assertHas("normalizeQimenDeityTh(p.deity_name_th)", "deity evidence normalizes Thai name before prompt");
assertHas("ก้านฟ้า ${p.heaven_stem_zh", "heaven stem evidence included");
assertHas("ก้านดิน ${p.earth_stem_zh", "earth stem evidence included");
assertHas("formatStemResponse(p.stem_response)", "stem response evidence included");
assertHas("function qimenStemResponseIsContextOnly", "stem_response context-only helper");
assertHas("verdict_allowed === false", "stem context-only detects verdict_allowed=false");
assertHas("quality || stemResponse?.effective_quality", "stem context-only detects quality/effective_quality");
assertHas("context_only", "stem context-only quality value");
assertHas("function formatEngineReadiness", "engine readiness formatter");
assertHas("stem_response_policy", "stem policy transmitted");
assertHas("stemResponse.engine_readiness", "stem readiness transmitted");
assertHas("stemResponse.caveat_th", "stem caveat transmitted");
assertHas("ยังไม่อนุญาตให้ฟันธงจากก้าน", "prompt carries non-verdict policy in Thai");
assertNotHas("verdict_allowed=false", "raw verdict flag must not reach Sifu prompt");
assertBlockHas(stemFormatter, "qimenStemResponseIsContextOnly(stemResponse)", "formatStemResponse uses context-only branch");
assertBlockHas(stemFormatter, "stemResponse.title_th || stemResponse.status_th", "context-only stem uses Thai title/status");
assertBlockHas(stemFormatter, "stemResponse.beginner_th || stemResponse.status_th", "context-only stem uses Thai beginner/status");
assertBlockHas(stemFormatter, "stemResponse.caveat_th", "context-only stem includes Thai caveat");
assertBlockHas(stemFormatter, "อ่านประกอบเท่านั้น", "context-only stem says read as context only");
assertBlockHas(stemFormatter, "ไม่ใช่คำตัดสิน", "context-only stem says not a verdict");
assertBlockHas(stemFormatter, "stemResponse.is_source_governed", "hour source-governed route preserved");
assertBlockHas(stemFormatter, "sourceRefText(stemResponse.source_trace || stemResponse.source_refs", "hour source-governed refs preserved");
assertBlockNotHas(stemFormatter, "ยังไม่มี source-governed verdict", "stem formatter must not hide real context-only stem_response");
assertHas("formatPalaceSourceFlags(p)", "source flags evidence included");
assertHas("formatAdvancedQimenLayers(p)", "advanced palace layer evidence included");
assertHas("qimenToneThai", "Thai tone mapper");
assertHas("qimenConfidenceThai", "Thai confidence mapper");
assertHas("const toneRaw = r.tone || r.kind", "beginner reason reads raw tone only as input");
assertHas("ระดับ: ${qimenToneThai(toneRaw)}", "beginner reason tone passes through Thai mapper");
assertHas("const levelRaw = p.display_level;", "display level checks only explicit display field presence");
assertHas("const level = levelRaw ? qimenToneThai(levelRaw) : \"ไม่ระบุ\"", "missing display level must not default to medium");
assertHas("ระดับระบบ ${level}", "raw display level not rendered directly");
assertBlockHas(palaceLineFormatter, "const levelRaw = p.display_level;", "palace line reads only explicit display_level");
assertBlockNotHas(palaceLineFormatter, "p.display_level ||", "palace line must not fallback to tier/quality/beginner level");
assertBlockHas(palaceLineFormatter, "levelRaw ? qimenToneThai(levelRaw) : \"ไม่ระบุ\"", "palace line only translates real level values");
assertBlockHas(sifuChartContextGuard, "normalizeQimenSystemType(systemTypeHint || chart?.system_type || chart?.chart_type)", "Sifu chart context guard reads system_type/hint only");
assertBlockHas(sifuChartContextGuard, "[\"day\", \"month\", \"year\"].includes(systemType)", "Sifu chart context guard only applies to DMY scopes");
assertBlockNotHas(sifuChartContextGuard, "|| !!chart?.dmy_fushi_context", "Sifu chart context guard must not trigger from stale DMY metadata");
assertBlockHas(sifuChartContextGuard, "return !verdictAllowed", "Sifu chart context guard releases DMY only after explicit verdict allowance");
assertBlockHas(sifuApplyChartContextGuard, "code: \"context_only\"", "Sifu guarded reading forces context-only code");
assertBlockHas(sifuApplyChartContextGuard, "label_th: \"อ่านประกอบเท่านั้น\"", "Sifu guarded reading labels DMY as context-only in Thai");
assertBlockHas(sifuApplyChartContextGuard, "label_zh: \"待校\"", "Sifu guarded reading labels DMY as pending verification in Chinese");
assertBlockHas(sifuApplyChartContextGuard, "is_actionable: false", "Sifu guarded reading disables actionable DMY verdict");
assertBlockHas(sifuApplyChartContextGuard, "verdict_allowed: false", "Sifu guarded reading disables verdict");
assertBlockHas(sifuApplyChartContextGuard, "has_engine_score: false", "Sifu guarded reading prevents score fallback verdict");
assertBlockHas(sifuScoreLine, "คะแนนช่วยจัดลำดับ", "Sifu score line labels guarded DMY score as ranking/context");
assertBlockHas(sifuScoreLine, "อ่านประกอบเท่านั้น ไม่ใช่คำตัดสินฤกษ์", "Sifu score line blocks DMY score verdict");
assertBlockHas(palaceLineFormatter, "const reading = qimenSifuApplyChartContextGuard(p, chart, systemTypeHint)", "palace line uses guarded reading");
assertBlockHas(palaceLineFormatter, "qimenSifuScoreLine(p, reading)", "palace line uses guarded score wording");
assertBlockHas(palaceLineFormatter, "formatBeginnerReading(p, reading)", "palace line passes guarded reading into beginner formatter");
assertBlockHas(palaceLineFormatter, "formatAdvancedQimenLayers(p)", "palace line appends active advanced qimen layers");
assertBlockHas(advancedLayerLabelFormatter, "layer?.label_th", "advanced layer formatter prefers Thai label from engine");
assertBlockHas(advancedLayerLabelFormatter, "layer?.label_zh", "advanced layer formatter keeps Chinese label from engine");
assertBlockHas(advancedLayerFormatter, "p?.advanced_qimen_layers", "advanced layer formatter reads backend advanced_qimen_layers");
assertBlockHas(advancedLayerFormatter, "layer.active === true", "advanced layer formatter includes active engine layers only");
assertBlockHas(advancedLayerFormatter, "layer.formation_items", "advanced layer formatter can list real per-palace formation items");
assertBlockHas(advancedLayerFormatter, "ไม่มีผลกับคะแนน", "advanced layer formatter states no score effect");
assertBlockHas(advancedReadinessFormatter, "chart?.advanced_qimen_layer_readiness", "advanced readiness formatter reads chart readiness packet");
assertBlockHas(advancedReadinessFormatter, "ยังไม่เปิดตรวจ", "advanced readiness distinguishes disabled formulas");
assertBlockHas(advancedReadinessFormatter, "ไม่ได้แปลว่าสูตรนั้นเกิดจริงในวัง", "advanced readiness blocks readiness-as-active-formula misuse");
assertBlockHas(mergedUiContextFlags, "...asPacketArray(p?.ui_flags)", "merged flags reads ui_flags");
assertBlockHas(mergedUiContextFlags, "...asPacketArray(p?.context_flags)", "merged flags also reads context_flags");
assertBlockHas(mergedUiContextFlags, "seen.has(key)", "merged flags deduplicates ui/context duplicates");
assertBlockHas(uiFlagsFormatter, "qimenMergedUiContextFlags(p)", "ui flags formatter uses merged ui/context flags");
assertBlockHas(uiFlagsFormatter, "formatQimenFlagBranchEvidence(flag)", "ui flags formatter appends branch evidence when backend sends it");
assertBlockHas(uiFlagsFormatter, "ถ้าป้ายใดไม่มีหลักฐานกิ่ง ห้ามอธิบายว่าติดเพราะกิ่งใด", "ui flags formatter blocks inferred branch evidence");
assertBlockHas(functionBlock("formatPalaceSourceFlags"), "qimenMergedUiContextFlags(p).filter", "source flags formatter uses merged ui/context flags");
assertBlockHas(palaceSignalFormatter, "formatQimenUiFlags(p)", "palace signal evidence includes ui flags");
assertBlockHas(palaceSignalFormatter, "formatPalaceLegacyFlags(p)", "palace signal evidence includes legacy flags");
assertBlockHas(palaceSignalFormatter, "formatPalaceSourceFlags(p)", "palace signal evidence includes source flags");
assertBlockHas(flagBranchEvidenceFormatter, "asPacketArray(flag?.branch_evidence)", "branch evidence formatter reads backend branch_evidence array");
assertBlockHas(flagBranchEvidenceFormatter, "item.matched_branch_zh", "branch evidence formatter reads matched_branch_zh");
assertBlockHas(flagBranchEvidenceFormatter, "item.matched_branches_zh", "branch evidence formatter reads matched_branches_zh");
assertBlockHas(flagBranchEvidenceFormatter, "qimenBranchList", "branch evidence formatter maps branch codes to Thai-first labels");
assertBlockHas(flagBranchEvidenceFormatter, "หลักฐานกิ่ง:", "branch evidence formatter labels evidence in Thai");
assertBlockHas(branchEvidenceLayerLabel, "code === \"YI_MA\"", "branch evidence layer labels sky horse context");
assertBlockHas(branchEvidenceLayerLabel, "code === \"GUI_REN\"", "branch evidence layer labels nobleman context");
assertBlockHas(branchEvidenceLayerLabel, "code === \"KONG_WANG\"", "branch evidence layer labels void context");
assertBlockHas(branchEvidenceLayerLabel, "code === \"RI_SHI_CHONG\"", "branch evidence layer labels day/hour clash context");
assertBlockHas(palaceBranchEvidenceSummary, "qimenContextFlagIsActive(flag)", "palace branch evidence summary uses active flags only");
assertBlockHas(palaceBranchEvidenceSummary, "formatQimenFlagBranchEvidence(flag)", "palace branch evidence summary uses real backend evidence");
assertBlockHas(palaceBranchEvidenceSummary, "ยังไม่มีหลักฐานกิ่งรายวังจากระบบ", "palace branch evidence summary has no-evidence caveat");
assertBlockHas(selectedPalaceCueFormatter, "แนวตอบวังที่เลือก 選宮讀法", "selected palace cue Thai-first heading");
assertBlockHas(selectedPalaceCueFormatter, "qimenSifuApplyChartContextGuard(p, chart, systemTypeHint)", "selected palace cue uses guarded reading");
assertBlockHas(selectedPalaceCueFormatter, "สถานะวังนี้", "selected palace cue exposes guarded reading status");
assertBlockHas(selectedPalaceCueFormatter, "อ่านประกอบเท่านั้น ไม่ใช้ฟันธง", "selected palace cue blocks DMY guarded verdict");
assertBlockHas(selectedPalaceCueFormatter, "หลักฐานหลัก", "selected palace cue lists core evidence");
assertBlockHas(selectedPalaceCueFormatter, "เหตุผลระบบ", "selected palace cue lists system reasons");
assertBlockHas(selectedPalaceCueFormatter, "ป้ายสัญญาณ", "selected palace cue lists flags");
assertBlockHas(selectedPalaceCueFormatter, "หลักฐานกิ่งของป้าย", "selected palace cue lists branch evidence separately");
assertBlockHas(selectedPalaceCueFormatter, "formatPalaceBranchEvidenceSummary(p)", "selected palace cue uses palace branch evidence summary");
assertBlockHas(selectedPalaceCueFormatter, "ก้านตอบสนอง 十干克應", "selected palace cue lists stem response");
assertBlockHas(selectedPalaceCueFormatter, "ต้องเช็กต่อ", "selected palace cue lists check-next");
assertBlockHas(selectedPalaceCueFormatter, "ถ้าขาดประตู/ดาว/เทพ/ก้าน/เหตุผล", "selected palace cue blocks incomplete verdicts");
assertBlockHas(selectedPalaceCueFormatter, "formatBeginnerReasons(reading, 4)", "selected palace cue uses bounded system reasons");
assertBlockHas(selectedPalaceCueFormatter, "formatCheckNext(reading, 3)", "selected palace cue uses bounded check-next");
assertBlockNotHas(selectedPalaceCueFormatter, "ใน packet", "selected palace cue avoids dev packet wording");
assertBlockHas(traceItemFormatter, "item.summary_th || item.detail_th", "trace item includes Thai source summary/detail");
assertBlockHas(traceItemFormatter, "item.source_summary_th || item.source_detail_th", "trace item includes engine ui flag source summary/detail");
assertBlockHas(traceItemFormatter, "item.negated_by", "trace item carries negation evidence");
assertBlockHas(traceItemFormatter, "เหตุผล:", "trace item renders reason label Thai-first");
assertBlockHas(beginnerFormatter, "support_count", "beginner reading includes support evidence count");
assertBlockHas(beginnerFormatter, "caution_count", "beginner reading includes caution evidence count");
assertBlockHas(beginnerFormatter, "hard_count", "beginner reading includes hard evidence count");
assertHas("sourceRefText", "source ref sanitizer");
assertBlockHas(sourceRefFormatter, "raw.source_label_th || raw.source_title_th || raw.title_th", "source refs prefer Thai source label/title");
assertBlockHas(sourceRefFormatter, "raw.source_label_zh || raw.source_title_zh || raw.title_zh", "source refs keep Chinese secondary label/title");
assertBlockHas(sourceRefFormatter, "raw.source_id || raw.id || raw.source", "source refs retain stable source id fallback");
assertBlockHas(sourceRefFormatter, "packetText(id, \"แหล่งอ้างอิง\")", "source refs fallback remains Thai");
assertBlockHas(sourceRefFormatter, "return [label, line].filter(Boolean).join(\":\")", "source refs retain line range after Thai label");
assertHas("replace(/\\\\/g, \"/\")", "source path backslash sanitizer");
assertHas("compact.split(\"/\").pop()", "source path basename sanitizer");
assertHas("slice(0, 3)", "bounded source/reason output");
assertHas("ผังเวลา (QiMen Chart):", "chart block label");
assertHas("แหล่งความรู้ฉีเหมิน", "source packet label");
assertHas("ผังตั้งต้น 元局", "Thai-first yuan ju label");
assertHas("ดาวนำ 值符", "Thai-first value star label");
assertHas("ประตูนำ 值使", "Thai-first value door label");
assertHas("หัวก้าน 旬首", "Thai-first xun leader label");
assertHas("ก้านหลบ 遁干", "Thai-first dun stem label");
assertHas("สายเทพ 八神", "Thai-first deity variant label");
assertHas("ใช้สูตร 值符隨干 / 值使隨支 จากข้อมูลผังจริง", "fushi formula caveat");
assertHas("วังดาวนำ 值符 / วังประตูนำ 值使 คือวังสำคัญที่ต้องอ่าน ไม่ใช่วังดีอัตโนมัติ", "lead palace not auto-good guard");
assertHas("รูปแบบผสม Compound Formations", "Thai-first compound formations heading");
assertBlockHas(fushiLineFormatter, "ดาวนำ 值符", "fushi formatter renders value star Thai-first");
assertBlockHas(fushiLineFormatter, "ประตูนำ 值使", "fushi formatter renders value door Thai-first");
assertBlockHas(fushiLineFormatter, "หัวก้าน 旬首", "fushi formatter renders xun leader Thai-first");
assertBlockHas(fushiLineFormatter, "qimenPalaceRef", "fushi formatter uses Thai palace ref");
assertBlockHas(fushiLineFormatter, "ใช้สูตร 值符隨干 / 值使隨支 จากข้อมูลผังจริง", "fushi formatter carries formula caveat");
assertBlockNotHas(fushiLineFormatter, "@宮", "fushi formatter must not render raw @宮 syntax");
assertBlockNotHas(fushiLineFormatter, "值符=", "fushi formatter must not render raw equals syntax");
assertBlockNotHas(fushiLineFormatter, "值使=", "fushi formatter must not render raw equals syntax");
assertBlockHas(chartAxisFormatter, "เสายาม", "chart axis formatter renders Thai hour pillar label");
assertBlockHas(chartAxisFormatter, "หัวก้าน 旬首", "chart axis formatter renders xun leader Thai-first");
assertBlockHas(chartAxisFormatter, "ก้านหลบ 遁干", "chart axis formatter renders dun stem Thai-first");
assertBlockHas(chartAxisFormatter, "สายเทพ 八神", "chart axis formatter renders deity variant Thai-first");
assertBlockNotHas(chartAxisFormatter, "八神派別", "chart axis formatter must not expose raw Chinese-first label");
const fourPillarsLine = route.indexOf("สี่เสาเวลา 四柱: ${formatQimenPillars(chart)}");
const timeContextLine = route.indexOf("บริบทเวลา 時間標記: ${formatQimenTimeContext(chart)}");
assert(fourPillarsLine >= 0 && timeContextLine > fourPillarsLine, "time context follows four pillars before source");
assertHas("ผังเวลา (QiMen Chart):\\n${qimenText}\\n${canonBlock}", "prompt body places chart before source packet");

assertNotHas("Yuan-Ju:", "old English-first Yuan-Ju label");
assertNotHas("旬首 ${chart.xun_hour_zh", "old Chinese-first xun leader interpolation");
assertNotHas("遁干 ${chart.dun_gan_zh", "old Chinese-first dun stem interpolation");
assertNotHas("值符=${chart.chief_star_code", "old raw fushi fallback");
assertNotHas("@宮", "old raw palace syntax");
assertNotHas("รูปเกมผสม", "old unclear Thai compound label");
assertNotHas("file_path", "internal path leak in formatter");
assertNotHas("Source ID: ${s.id}", "old source-id-only packet format");
assertNotHas("trace.push(s.id)", "old source-id-only trace format");
assertNotHas("source=${", "raw source equals formatter");
assertNotHas("confidence=${", "raw confidence equals formatter");
assertNotHas("chart_source=", "raw chart source key");
assertNotHas("system_type=${systemType}", "raw system_type key");
assertNotHas("flags: ${flags}", "raw flags label");
assertNotHas("full81=${", "raw boolean full81 marker");
assertNotHas("[r.kind, r.tone].filter(Boolean).join(\"/\")", "raw kind/tone join");

console.log("PASS qimen-sifu beginner prompt wire");
